name: Pipeline DevSecOps

on: 
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  secret_scanning: 
    name: secret scan
    runs-on: ubuntu-latest
    steps:
    - name: Descargar código
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        
    - name: Gitleaks
      uses: gitleaks/gitleaks-actions@v3.0.0

  dependency_scan:
    needs: [secret_scanning]
    name: SCA Scan
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v6

      - name: Instalar dependencias
        run: npm install

      - name: Análisis SCA
        run: npm audit
        
  static_scan:     
    needs: [secret_scanning]
    if: always()
    name: SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Descagar código
        uses: actions/checkout@v6

      - name: Semgrep
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            -w /src \
            semgrep/semgrep \
            semgrep scan \
            --config p/default \
            --sarif \
            --output semgrep.sarif \
            --error || true

       - name: subir resultados
         uses: github/codeql-action/upload-sarif@v4
         with:
           sarif_file: results.sarif
           category: my-analysis-tool
